export const mockItems = [

  // JACKETS
  // item1=brown jacket, item6=grey jacket, item14=beige jacket, item15=teal jacket, item16=navy jacket, item17=green bomber
  {
    id: '1',
    title: 'Brown Casual Jacket',
    price: 3500,
    condition: 'Good',
    demand: 'high',
    size: 'M',
    category: 'jackets',
    imageUrl: require('../../assets/item1.jpg'),
  },
  {
    id: '2',
    title: 'Grey Zip Jacket',
    price: 2800,
    condition: 'Like New',
    demand: 'high',
    size: 'L',
    category: 'jackets',
    imageUrl: require('../../assets/item6.jpg'),
  },
  {
    id: '3',
    title: 'Beige Classic Jacket',
    price: 3100,
    condition: 'Good',
    demand: 'moderate',
    size: 'M',
    category: 'jackets',
    imageUrl: require('../../assets/item14.jpg'),
  },
  {
    id: '4',
    title: 'Teal Light Jacket',
    price: 2200,
    condition: 'Excellent',
    demand: 'moderate',
    size: 'S',
    category: 'jackets',
    imageUrl: require('../../assets/item15.jpg'),
  },
  {
    id: '5',
    title: 'Navy Zip Jacket',
    price: 2600,
    condition: 'Good',
    demand: 'high',
    size: 'M',
    category: 'jackets',
    imageUrl: require('../../assets/item16.jpg'),
  },
  {
    id: '6',
    title: 'Green Bomber Jacket',
    price: 3200,
    condition: 'Good',
    demand: 'high',
    size: 'L',
    category: 'jackets',
    imageUrl: require('../../assets/item17.jpg'),
  },

  // SHIRTS
  // item2=white shirt, item18=blue patch shirt, item19=blue shirt, item20=lavender shirt
  {
    id: '7',
    title: 'White Dress Shirt',
    price: 2268,
    condition: 'Like New',
    demand: 'moderate',
    size: 'L',
    category: 'shirts',
    imageUrl: require('../../assets/item2.jpg'),
  },
  {
    id: '8',
    title: 'Blue Patch Shirt',
    price: 1450,
    condition: 'Good',
    demand: 'moderate',
    size: 'M',
    category: 'shirts',
    imageUrl: require('../../assets/item18.jpg'),
  },
  {
    id: '9',
    title: 'Blue Oxford Shirt',
    price: 1600,
    condition: 'Excellent',
    demand: 'moderate',
    size: 'M',
    category: 'shirts',
    imageUrl: require('../../assets/item19.jpg'),
  },
  {
    id: '10',
    title: 'Lavender Formal Shirt',
    price: 1800,
    condition: 'Good',
    demand: 'moderate',
    size: 'L',
    category: 'shirts',
    imageUrl: require('../../assets/item20.jpg'),
  },

  // TEES
  // item9=black graphic tee, item10=grey tee, item11=black tee, item12=maroon polo
  {
    id: '11',
    title: 'Black Graphic Tee',
    price: 850,
    condition: 'Good',
    demand: 'high',
    size: 'M',
    category: 'tees',
    imageUrl: require('../../assets/item9.jpg'),
  },
  {
    id: '12',
    title: 'Grey Basic Tee',
    price: 750,
    condition: 'Good',
    demand: 'moderate',
    size: 'S',
    category: 'tees',
    imageUrl: require('../../assets/item10.jpg'),
  },
  {
    id: '13',
    title: 'Black Slim Tee',
    price: 700,
    condition: 'Excellent',
    demand: 'moderate',
    size: 'M',
    category: 'tees',
    imageUrl: require('../../assets/item11.jpg'),
  },
  {
    id: '14',
    title: 'Maroon Polo Tee',
    price: 900,
    condition: 'Like New',
    demand: 'high',
    size: 'L',
    category: 'tees',
    imageUrl: require('../../assets/item12.jpg'),
  },

  // HOODIES
  // item4=maroon hoodie, item24=black hoodie, item25=mint hoodie, item26=white hoodie
  {
    id: '15',
    title: 'Maroon Pullover Hoodie',
    price: 1800,
    condition: 'Good',
    demand: 'high',
    size: 'M',
    category: 'hoodies',
    imageUrl: require('../../assets/item4.jpg'),
  },
  {
    id: '16',
    title: 'Classic Black Hoodie',
    price: 1145,
    condition: 'Good',
    demand: 'high',
    size: 'XL',
    category: 'hoodies',
    imageUrl: require('../../assets/item24.jpg'),
  },
  {
    id: '17',
    title: 'Mint Green Hoodie',
    price: 1300,
    condition: 'Like New',
    demand: 'moderate',
    size: 'S',
    category: 'hoodies',
    imageUrl: require('../../assets/item25.jpg'),
  },
  {
    id: '18',
    title: 'White Zip Hoodie',
    price: 1400,
    condition: 'Excellent',
    demand: 'moderate',
    size: 'M',
    category: 'hoodies',
    imageUrl: require('../../assets/item26.jpg'),
  },

  // OVERCOATS
  // item3=black long coat, item21=trench coat, item22=grey coat, item23=navy coat
  {
    id: '19',
    title: 'Black Long Overcoat',
    price: 5500,
    condition: 'Good',
    demand: 'high',
    size: 'M',
    category: 'overcoats',
    imageUrl: require('../../assets/item3.jpg'),
  },
  {
    id: '20',
    title: 'Camel Trench Coat',
    price: 3800,
    condition: 'Good',
    demand: 'moderate',
    size: 'M',
    category: 'overcoats',
    imageUrl: require('../../assets/item21.jpg'),
  },
  {
    id: '21',
    title: 'Grey Formal Overcoat',
    price: 4500,
    condition: 'Excellent',
    demand: 'high',
    size: 'L',
    category: 'overcoats',
    imageUrl: require('../../assets/item22.jpg'),
  },
  {
    id: '22',
    title: 'Navy Classic Coat',
    price: 4000,
    condition: 'Good',
    demand: 'moderate',
    size: 'S',
    category: 'overcoats',
    imageUrl: require('../../assets/item23.jpg'),
  },

  // JEANS
  // item27=blue jeans, item28=slim jeans, item29=navy jeans, item30=light jeans
  {
    id: '23',
    title: 'Classic Blue Jeans',
    price: 1800,
    condition: 'Good',
    demand: 'high',
    size: 'M',
    category: 'jeans',
    imageUrl: require('../../assets/item27.jpg'),
  },
  {
    id: '24',
    title: 'Slim Fit Jeans',
    price: 2100,
    condition: 'Excellent',
    demand: 'high',
    size: 'L',
    category: 'jeans',
    imageUrl: require('../../assets/item28.jpg'),
  },
  {
    id: '25',
    title: 'Navy Skinny Jeans',
    price: 1600,
    condition: 'Good',
    demand: 'moderate',
    size: 'S',
    category: 'jeans',
    imageUrl: require('../../assets/item29.jpg'),
  },
  {
    id: '26',
    title: 'Light Wash Jeans',
    price: 1900,
    condition: 'Like New',
    demand: 'moderate',
    size: 'M',
    category: 'jeans',
    imageUrl: require('../../assets/item30.jpg'),
  },

  // JOGGERS
  // item7=navy joggers, item13=grey joggers, item31=black joggers
  {
    id: '27',
    title: 'Navy Slim Joggers',
    price: 1100,
    condition: 'Good',
    demand: 'high',
    size: 'M',
    category: 'joggers',
    imageUrl: require('../../assets/item7.jpg'),
  },
  {
    id: '28',
    title: 'Grey Casual Joggers',
    price: 1000,
    condition: 'Good',
    demand: 'moderate',
    size: 'L',
    category: 'joggers',
    imageUrl: require('../../assets/item13.jpg'),
  },
  {
    id: '29',
    title: 'Black Slim Joggers',
    price: 1200,
    condition: 'Excellent',
    demand: 'high',
    size: 'S',
    category: 'joggers',
    imageUrl: require('../../assets/item13.jpg'),
  },

  // SHORTS
  // item5=black Nike shorts, item32=white shorts, item8=khaki shorts
  {
    id: '30',
    title: 'Black Nike Shorts',
    price: 950,
    condition: 'Excellent',
    demand: 'high',
    size: 'L',
    category: 'shorts',
    imageUrl: require('../../assets/item5.jpg'),
  },
  {
    id: '31',
    title: 'White Casual Shorts',
    price: 800,
    condition: 'Good',
    demand: 'moderate',
    size: 'M',
    category: 'shorts',
    imageUrl: require('../../assets/item32.jpg'),
  },
  {
    id: '32',
    title: 'Khaki Chino Shorts',
    price: 850,
    condition: 'Good',
    demand: 'moderate',
    size: 'M',
    category: 'shorts',
    imageUrl: require('../../assets/item8.jpg'),
  },
];